![jupyter](img/logo-itq.png)

# Normalización  
## PAO26-27 - Python 01

![jupyter](img/logo-py.png)

**Nombre:** *David Ruiz*
Ejercicios de normalización 

In [3]:
from sklearn import preprocessing
import numpy as np

In [5]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [6]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

In [7]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [5]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_train)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_train_norm_2 = f.transform(X_train)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

True


In [10]:
# Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO "transform", NO EL "fit")
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  4., -1.]])
print(X_test)
# Normalizar los datos de "X_test"

X_test_norm = normalizer.transform(X_test)
# ???
# Salida del resultado
print(X_test_norm)

[[ 1. -3.  2.]
 [ 3.  0.  0.]
 [ 0.  4. -1.]]
[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


In [12]:
# Normalización 
X_test_norm = normalizer.transform(X_test)

# Usando el objeto "f" (que ya fue entrenado con X_train)
X_test_norm_2 = f.transform(X_test)

# Comparación
print(np.array_equiv(X_test_norm, X_test_norm_2))

True


In [21]:
# Otro ejercicio
X_train2 = np.array([[10., 3., 1.],
                    [20., 15., 2.],
                    [15., 13., 3.]])

print(X_train2)

# 🔹 Normalización
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train2)
print(X_train_norm)

[[10.  3.  1.]
 [20. 15.  2.]
 [15. 13.  3.]]
[[0.         0.         0.        ]
 [1.         1.         0.5       ]
 [0.5        0.83333333 1.        ]]


### Repositorio
* https://github.com/enderliliessad-pixel/Cuaderno_Machine2.git